### ISSUE TITLE
桌面版瀏覽器觸屏問題

### ISSUE THREAD

**Issue by chinuno-usami** [yjhatfdu/LLpractice#3]
唉不知道該到哪裏反饋就在這裏開個issue吧
在我surface pro3上面不管是chrome還是firefox在點擊note的時候種是會卡噸一下，不能正常判定
另外在ie卡載入，edge瀏覽器可以載入但是只要一點note就會都消失掉．希望能fix一下

**Comment by chinuno-usami** [comment]
知道問題在哪了．close了吧．surface pro3的分辨率特別高，然後全屏或則最大化的時候就會lag了．在調整窗口大小之後不會出現這樣的問題了．不過好小．．．．

**Comment by yjhatfdu** [comment]
是在线版本还是这个版本？

**Comment by chinuno-usami** [comment]
噫。竟然还回复了
就是https://m.tianyi9.com 这个

2015-10-30 3:25 GMT+08:00 yjhatfdu <notifications@github.com>:
