### ISSUE TITLE
JSON与其他资源的Web API的使用申请

### ISSUE THREAD

**Issue by Kailang** [yjhatfdu/LLpractice#4]
您好，在下是一个业余东方同人手机音乐游戏开发者。
在这里正式申请对您经营的音乐游戏平台（m.tianyi9.com）进行HTTP请求的许可。

## 缘由
在下因为一直苦于没有优质的铺面资源，而且根据音频文件生成的铺面极端不可玩，原来使用MIDI文件生成铺面，并于实时根据MIDI合成音乐。
音乐合成库的Repository可在这里查阅：（github.com/DotLab/Midif）

但是，在手机上实时合成的音乐即使经过大量优化，其音质与性能仍然达到不了直接播放音频的传统音乐游戏。
您所制作的音乐游戏（github.com/yjhatfdu/LLpractice）及其平台（m.tianyi9.com）拥有大量优质的铺面资源与活跃的用户基础。
于是，在下想基于您平台上的资源开发一个新的非商用手机音乐游戏。
游戏的Repository可以在这里查阅：（github.com/DotLab/Love-Live-Practice）

## 计划
作为SIF类型音乐游戏，除了游戏本身外，需要支持抽卡与队伍编成。
因为是用户提供内容，需要支持卡牌编辑与卡牌投票。
在下已经确认了一组东方的同人角色立绘的许可（seiga.nicovideo.jp/seiga/im3189645），计划用这些立绘来给用户制作卡牌。
制作卡牌与新增排行系统等其他内容，均由在下编写与运营（thlive.cc）
由于业余的时间有限，暂时不计划实现卡牌部分的游戏功能。

### 已实现的功能
- 加载、读取、缓存默认列表中的Live及Live的详细信息
- 加载、读取、缓存、自动弹奏任意Live的Map
- 加载、读取、缓存任意Live对应的Cover与BGM
- 离线模式使用缓存进行游戏

### 待实现的功能
- 游戏本体（不使用LLpractice提供的背景，不使用SIF相同的游戏UI设计）
- 延时调整
- 手气不错
- 加载、读取、缓存分区列表中的Live及Live的详细信息

### 计划中的功能
- 查看评论
- 游戏本体2（新的游戏UI设计）

## Web API
因为游戏UI动画及下载队列设计延时，Web API的使用不会高于普通浏览器。
下表包含了设计的API并行下载限制与下载延时。
### 正在使用的API
```
m.tianyi9.com/API/getlivelist?type=public&offset=<offset>&limit=24 (并行：1，延时：>1s，不缓存)
m.tianyi9.com/API/getlive?live_id=<live_id> (并行：4，延时：>1s，始终更新缓存)
m.tianyi9.com/upload/<path> (并行：4，延时：>0.2s，缓存一次不再更新)
```
### 计划使用的API
```
m.tianyi9.com/API/getlivelist?type=category&offset=<offset>&limit=24&category=<category> (并行：1，延时：>1s，不缓存)
m.tianyi9.com/API/getcomments?live_id=<live_id>&limit=20&offset=<offset> (并行：1，延时：>1s，不缓存)
```

## 与Android版LLpractice
上述音乐游戏不同于已经存在的Android版LLpractice（github.com/loveyanbei/LLPractice_Publish）在下几点：
1. 使用Unity游戏引擎
2. 全平台支持（Destop / Android / iOS）
3. 不同的游戏UI设计
4. 更好的游戏体验
5. （未来可能）支持抽卡

## 许可
本游戏仅供教育用途使用。
游戏源码及素材中在下制作的部分许可未定。
游戏源码所有Dependency均为Pulibc Domain。
游戏源码没有参考任何游戏。
游戏中LLpractice提供的铺面、图片、音频的版权遵循LLpractice的许可。
游戏中其他图片与音频的版权归原版权所有人所有。

## 申请
请允许在下使用您音乐游戏平台（m.tianyi9.com）的Web API来制作一个手机音乐游戏。
在下会最大限度地修改游戏本身来满足您提出的要求从而获得您的同意。

Kailang

**Comment by Kailang** [comment]
未被允许。

**Comment by loveyanbei** [comment]
emmm，多跟裙裙学
欢迎未来加入我司（裙裙的）
